import pyautogui as gui
import time


gui.hotkey('alt', 'tab')
gui.click(x=1502, y=118)
time.sleep(1)
for _ in range(11):
    gui.hotkey('ctrl', 'c')
    time.sleep(1)
    gui.click(x=309, y=181)
    time.sleep(1)
    gui.hotkey('ctrl', 'a')
    time.sleep(1)
    gui.hotkey('ctrl', 'v')
    time.sleep(1)
    gui.click(x=277, y=101)
    time.sleep(2)
    gui.click(x=25, y=273)
    time.sleep(1)
    gui.click(x=806, y=103)
    time.sleep(1)
    gui.click(x=338, y=225)
    time.sleep(1)
    gui.write('BA_OFIC_R08')
    time.sleep(1)
    gui.click(x=50, y=469)
    time.sleep(1)
    gui.click(x=47, y=492)
    time.sleep(1)
    gui.click(x=649, y=716)
    time.sleep(1)
    gui.click(x=29, y=53)
    time.sleep(1)
    gui.hotkey('alt', 'tab')
    time.sleep(1)
    gui.press('down')
    time.sleep(1)